### ISSUE TITLE
Add `data-closed` attribute.

### ISSUE THREAD

**Issue by fabien-ml** [kobaltedev/kobalte#114]
**Is your feature request related to a problem? Please describe.**
Add `data-closed` attribute to components that has the `data-expanded` attribute.

**Additional context**
More understandable way to deal with css animation:

```css
.popover__content {
  z-index: 50;
  max-width: min(calc(100vw - 16px), 380px);
  border: 1px solid hsl(240 5% 84%);
  border-radius: 6px;
  padding: 12px;
  background-color: white;
  box-shadow: 0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1);
  transform-origin: var(--kb-popover-content-transform-origin);
}

.popover__content[data-closed] {
  animation: contentHide 250ms ease-in forwards;
}

.popover__content[data-expanded] {
  animation: contentShow 250ms ease-out;
}
```
