### ISSUE TITLE
Dropdowns and context menus can leave user input disabled

### ISSUE THREAD

**Issue by ExoticMatter** [kobaltedev/kobalte#160]
**Describe the bug**
Rapidly opening and closing a dropdown or context menu can leave input disabled for the entire page. This seems to occur when attempting to re-open a menu before it has disappeared.

**To Reproduce**

1. Go to the [dropdown menu example](https://kobalte.dev/docs/core/components/dropdown-menu#example)
2. Rapidly click-spam the menu button
3. After 3 or so clicks,  the page no longer accepts user input

Alternate steps:

1. Go to the [context menu example](https://kobalte.dev/docs/core/components/context-menu#example)
2. Rapidly spam right clicks
3. After 3 or so right clicks, the page no longer accepts user input

In both cases, inspect element reveals the page `<body>` has `style="pointer-events: none;"`.

**Expected behavior**
Dropdowns and context menus should not permanently disable user input.

**Desktop:**

- OS: Debian 11
- Browser: Firefox 102.9.0esr

**Extra information**: CSS transitions are required for this bug to occur, so I have recreated a minimal test case. Extending the length of the transition makes it easier to trigger the bug.

JSX:

```html
<DropdownMenu.Root>
  <DropdownMenu.Trigger>
    Foobar
  </DropdownMenu.Trigger>
  <DropdownMenu.Portal>
    <DropdownMenu.Content class="menu-body">
      <DropdownMenu.Item>
        <DropdownMenu.ItemLabel>Foo</DropdownMenu.ItemLabel>
      </DropdownMenu.Item>
    </DropdownMenu.Content>
  </DropdownMenu.Portal>
</DropdownMenu.Root>
```

CSS:

```css
.menu-body {
  animation: hide-content 1s ease-out;
}

.menu-body[data-expanded] {
  animation: show-content 1s ease-out;
}

@keyframes show-content {
  0% { opacity: 0; }
  100% { opacity: 1; }
}

@keyframes hide-content {
  0% { opacity: 1; }
  100% { opacity: 0; }
}
```
