### ISSUE TITLE
AlertDialog/Dialog animation broken when using controlled-open

### ISSUE THREAD

**Issue by xhanl** [kobaltedev/kobalte#505]
**Describe the bug**
- Follow the [#controlled-open](https://kobalte.dev/docs/core/components/alert-dialog#controlled-open), use a singal to control dialog open.
- When the prop `open` false, It will disappear directly without any exit animation.
- Both `AlertDialog` and `Dialog` have the same problem

**To Reproduce**

1. Copy the [Example](https://kobalte.dev/docs/core/components/alert-dialog#example) from doc.
2. Create a custom button by following the [#controlled-open](https://kobalte.dev/docs/core/components/alert-dialog#controlled-open)
3. [Minimal Reproduction](https://stackblitz.com/edit/solid-vite-xgguvc?file=src%2FDialogDemo.tsx)

**Expected behavior**
When closing the Dialog with prop open, there should be a correct exit animation.

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Safari
- Version: 15.0.1

**Comment by masylum** [comment]
Hey there!

I had the same bug, but it actually wasn't a bug. Kobalte uses https://corvu.dev/docs/utilities/presence/ underneath. This means that it will wait until your animation is done. You are probably missing the out animation on the base class:

```css
.dialog__content {
  //...
  animation: contentHide 300ms ease-in forwards; // this one!
}
.dialog__content[data-expanded] {
  animation: contentShow 300ms ease-out;
}
```
